# Generated by Django 2.1.7 on 2020-01-27 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_first_name', models.CharField(default='', max_length=30)),
                ('profile_last_name', models.CharField(default='', max_length=30)),
                ('hospital', models.CharField(default='None', max_length=50)),
                ('adress_hospital', models.CharField(default='None', max_length=60)),
                ('phone_number', models.IntegerField(default='1')),
                ('caption', models.TextField(default='', max_length=750)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile_images')),
                ('buletin_picture', models.ImageField(blank=True, null=True, upload_to='images/buletin')),
                ('profile_doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('profile_first_name', 'profile_last_name'),
            },
        ),
    ]
